---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1608685/repositories/gungnanda.com
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp credits.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R game $DEPLOYPATH
    - /bin/cp -R portfolio $DEPLOYPATH
